import {defineConfig, type OxlintConfig} from 'oxlint';

const config: OxlintConfig = defineConfig({
    categories: {
        correctness: 'error',
    },
    env: {
        browser: true,
        node: true,
        serviceworker: true,
    },
    ignorePatterns: [
        '**/*.d.ts',
        '**/*.d.mts',
        '**/build/**',
        '**/dist/**',
        '**/sanity.types.ts',
    ],
    options: {
        typeAware: true,
    },
    overrides: [
        {
            // Tests hold long scenario tables.
            files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
            plugins: ['vitest'],
            rules: {
                'eslint/max-lines': 'off',
            },
        },
        {
            files: ['**/*.{js,jsx,mjs,cjs}'],
            plugins: ['oxc', 'unicorn'],
            rules: {
                'typescript/ban-ts-comment': 'off',
                'typescript/no-empty-object-type': 'off',
                'typescript/no-explicit-any': 'off',
                'typescript/no-misused-promises': 'off',
                'typescript/no-namespace': 'off',
                'typescript/no-require-imports': 'off',
                'typescript/no-unnecessary-type-assertion': 'off',
                'typescript/no-unnecessary-type-constraint': 'off',
                'typescript/no-unsafe-argument': 'off',
                'typescript/no-unsafe-assignment': 'off',
                'typescript/no-unsafe-call': 'off',
                'typescript/no-unsafe-enum-comparison': 'off',
                'typescript/no-unsafe-function-type': 'off',
                'typescript/no-unsafe-member-access': 'off',
                'typescript/no-unsafe-return': 'off',
                'typescript/only-throw-error': 'off',
                'typescript/prefer-promise-reject-errors': 'off',
                'typescript/require-await': 'off',
                'typescript/restrict-plus-operands': 'off',
            },
        },
    ],
    plugins: [
        'import',
        'oxc',
        'promise',
        'typescript',
        'unicorn',
    ],
    rules: {
        'eslint/func-style': ['error', 'expression'],
        'eslint/max-lines': [
            'error',
            {
                max: 300,
                skipBlankLines: true,
                skipComments: true,
            },
        ],
        'eslint/no-array-constructor': 'error',
        'eslint/no-case-declarations': 'error',
        'eslint/no-empty': 'error',
        'eslint/no-fallthrough': 'error',
        'eslint/no-prototype-builtins': 'error',
        'eslint/no-regex-spaces': 'error',
        'eslint/no-unexpected-multiline': 'error',
        'eslint/no-useless-assignment': 'error',
        'eslint/no-var': 'error',
        'eslint/prefer-const': 'error',
        'eslint/prefer-rest-params': 'error',
        'eslint/prefer-spread': 'error',
        'eslint/prefer-arrow-callback': 'error',
        'eslint/preserve-caught-error': 'error',
        // TypeScript already checks default and namespace imports.
        'import/default': 'off',
        'import/namespace': 'off',
        'import/no-absolute-path': 'error',
        'import/no-cycle': 'error',
        'import/no-duplicates': 'error',
        'import/no-self-import': 'error',
        'import/no-webpack-loader-syntax': 'error',
        'promise/no-multiple-resolved': 'error',
        'promise/no-promise-in-callback': 'warn',
        'promise/no-return-in-finally': 'error',
        'promise/param-names': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'warn',
        'typescript/no-misused-promises': [
            'error',
            {
                checksVoidReturn: false,
            },
        ],
        'typescript/no-namespace': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-unnecessary-type-assertion': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-argument': 'error',
        'typescript/no-unsafe-assignment': 'error',
        'typescript/no-unsafe-call': 'error',
        'typescript/no-unsafe-enum-comparison': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-unsafe-member-access': 'error',
        'typescript/no-unsafe-return': 'error',
        'typescript/only-throw-error': 'error',
        'typescript/prefer-promise-reject-errors': 'error',
        'typescript/require-await': 'error',
        'typescript/restrict-plus-operands': 'error',
    },
});

export default config;
