name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: "Use NodeJS 20"
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Config git user
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote set-url origin https://${{ github.actor }}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}

    - name: "NPM Identity"
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

    - name: "Install dependencies"
      run: yarn

    - name: "Build"
      run: yarn build:all

    - name: "Clean"
      run: |
        git update-index --assume-unchanged .npmrc
        git update-index --assume-unchanged .yarn/install-state.gz

    - name: "Version and publish"
      run: |
        npx lerna version --yes --conventional-commits --create-release github --message 'chore(release): publish'
        npx lerna publish from-package --no-verify-access --yes
